version: '1.0'
services:
  web:
    build: .
    image: dev_api
    restart: on-failure
    # depends_on:
      # - db
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - 8080:8080
    command: yarn run dev

  # db:
  #   image: postgres:11
  #   restart: on-failure
  #   ports:
  #     - "35432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: db
  #   volumes:
  #     - db:/var/lib/postgresql

# volumes:
#   db: {}